/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MidasMultinetworkRouterManagerInterface
  extends ethers.utils.Interface {
  functions: {
    "addLiquidity(address,address,uint256,uint256)": FunctionFragment;
    "getDexRouter()": FunctionFragment;
    "getDexRouterAddress()": FunctionFragment;
    "getNativeTokenAddress(uint256)": FunctionFragment;
    "getStableCoinAddress(uint256)": FunctionFragment;
    "getTokensValueInUSD(address,uint256)": FunctionFragment;
    "isInSwap()": FunctionFragment;
    "setChainlinkDataFeedsManager(address)": FunctionFragment;
    "setDexRouter(address)": FunctionFragment;
    "swapTokensForNativeToken(address,address,uint256)": FunctionFragment;
    "swapTokensForStableCoin(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDexRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDexRouterAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNativeTokenAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStableCoinAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensValueInUSD",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isInSwap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setChainlinkDataFeedsManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDexRouter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForNativeToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForStableCoin",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDexRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDexRouterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNativeTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStableCoinAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensValueInUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isInSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkDataFeedsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDexRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForNativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForStableCoin",
    data: BytesLike
  ): Result;

  events: {};
}

export class MidasMultinetworkRouterManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MidasMultinetworkRouterManagerInterface;

  functions: {
    addLiquidity(
      token: string,
      to: string,
      tokenAmount: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDexRouter(overrides?: CallOverrides): Promise<[string]>;

    getDexRouterAddress(overrides?: CallOverrides): Promise<[string]>;

    getNativeTokenAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStableCoinAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTokensValueInUSD(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isInSwap(overrides?: CallOverrides): Promise<[boolean]>;

    setChainlinkDataFeedsManager(
      _chainlinkDataFeedsManagerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDexRouter(
      _dexRouterAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForNativeToken(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForStableCoin(
      tokenAddress: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addLiquidity(
    token: string,
    to: string,
    tokenAmount: BigNumberish,
    ethAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDexRouter(overrides?: CallOverrides): Promise<string>;

  getDexRouterAddress(overrides?: CallOverrides): Promise<string>;

  getNativeTokenAddress(
    _networkId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getStableCoinAddress(
    _networkId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getTokensValueInUSD(
    _tokenAddress: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isInSwap(overrides?: CallOverrides): Promise<boolean>;

  setChainlinkDataFeedsManager(
    _chainlinkDataFeedsManagerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDexRouter(
    _dexRouterAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForNativeToken(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForStableCoin(
    tokenAddress: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addLiquidity(
      token: string,
      to: string,
      tokenAmount: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getDexRouter(overrides?: CallOverrides): Promise<string>;

    getDexRouterAddress(overrides?: CallOverrides): Promise<string>;

    getNativeTokenAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getStableCoinAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getTokensValueInUSD(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInSwap(overrides?: CallOverrides): Promise<boolean>;

    setChainlinkDataFeedsManager(
      _chainlinkDataFeedsManagerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDexRouter(
      _dexRouterAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    swapTokensForNativeToken(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapTokensForStableCoin(
      tokenAddress: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addLiquidity(
      token: string,
      to: string,
      tokenAmount: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDexRouter(overrides?: CallOverrides): Promise<BigNumber>;

    getDexRouterAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getNativeTokenAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStableCoinAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokensValueInUSD(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInSwap(overrides?: CallOverrides): Promise<BigNumber>;

    setChainlinkDataFeedsManager(
      _chainlinkDataFeedsManagerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDexRouter(
      _dexRouterAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForNativeToken(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForStableCoin(
      tokenAddress: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidity(
      token: string,
      to: string,
      tokenAmount: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDexRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDexRouterAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNativeTokenAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStableCoinAddress(
      _networkId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokensValueInUSD(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInSwap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setChainlinkDataFeedsManager(
      _chainlinkDataFeedsManagerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDexRouter(
      _dexRouterAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForNativeToken(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForStableCoin(
      tokenAddress: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
