/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TestTokenInterface extends ethers.utils.Interface {
  functions: {
    "BUSD()": FunctionFragment;
    "BUSDRewardsFeeBuy()": FunctionFragment;
    "BUSDRewardsFeeSell()": FunctionFragment;
    "BurnAddress()": FunctionFragment;
    "BurnFee()": FunctionFragment;
    "DevFeeBuy()": FunctionFragment;
    "DevFeeSell()": FunctionFragment;
    "DevWallet()": FunctionFragment;
    "MarketingFeeBuy()": FunctionFragment;
    "MarketingFeeSell()": FunctionFragment;
    "MarketingWallet()": FunctionFragment;
    "SetmaxSellTransactionAmount(uint256)": FunctionFragment;
    "_maxTxAmount()": FunctionFragment;
    "_maxWalletAmount()": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "automatedMarketMakerPairs(address)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "claim()": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "dividendTokenBalanceOf(address)": FunctionFragment;
    "dividendTracker()": FunctionFragment;
    "excludeFromFees(address,bool)": FunctionFragment;
    "excludeMultipleAccountsFromFees(address[],bool)": FunctionFragment;
    "getAccountDividendsInfo(address)": FunctionFragment;
    "getAccountDividendsInfoAtIndex(uint256)": FunctionFragment;
    "getClaimWait()": FunctionFragment;
    "getLastProcessedIndex()": FunctionFragment;
    "getNumberOfDividendTokenHolders()": FunctionFragment;
    "getTotalDividendsDistributed()": FunctionFragment;
    "getTradingIsEnabled()": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "isExcludedFromFees(address)": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "processDividendTracker(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "sellFeeIncreaseFactor()": FunctionFragment;
    "setAutomatedMarketMakerPair(address,bool)": FunctionFragment;
    "setBUSDRewardsFeeBuy(uint256)": FunctionFragment;
    "setBUSDRewardsFeesSell(uint256)": FunctionFragment;
    "setBurnFee(uint256)": FunctionFragment;
    "setDevFeeBuy(uint256)": FunctionFragment;
    "setDevFeeSell(uint256)": FunctionFragment;
    "setMarketingFeeBuy(uint256)": FunctionFragment;
    "setMarketingFeeSell(uint256)": FunctionFragment;
    "setswapTokensAtAmount(uint256)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalFees()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "tradingEnabledTimestamp()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uniswapV2Pair()": FunctionFragment;
    "uniswapV2Router()": FunctionFragment;
    "updateClaimWait(uint256)": FunctionFragment;
    "updateDevWallet(address)": FunctionFragment;
    "updateDividendTracker(address)": FunctionFragment;
    "updateGasForProcessing(uint256)": FunctionFragment;
    "updateUniswapV2Router(address)": FunctionFragment;
    "withdrawableDividendOf(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "BUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BUSDRewardsFeeBuy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUSDRewardsFeeSell",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BurnAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BurnFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "DevFeeBuy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DevFeeSell",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DevWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MarketingFeeBuy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MarketingFeeSell",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MarketingWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SetmaxSellTransactionAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_maxTxAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_maxWalletAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "automatedMarketMakerPairs",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dividendTokenBalanceOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "dividendTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeFromFees",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "excludeMultipleAccountsFromFees",
    values: [string[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountDividendsInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountDividendsInfoAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimWait",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastProcessedIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfDividendTokenHolders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDividendsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingIsEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isExcludedFromFees",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processDividendTracker",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellFeeIncreaseFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAutomatedMarketMakerPair",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBUSDRewardsFeeBuy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBUSDRewardsFeesSell",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBurnFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDevFeeBuy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDevFeeSell",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketingFeeBuy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketingFeeSell",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setswapTokensAtAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradingEnabledTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Pair",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Router",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateClaimWait",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDevWallet",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDividendTracker",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGasForProcessing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUniswapV2Router",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableDividendOf",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "BUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BUSDRewardsFeeBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUSDRewardsFeeSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BurnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BurnFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DevFeeBuy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DevFeeSell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DevWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MarketingFeeBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MarketingFeeSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MarketingWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SetmaxSellTransactionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_maxTxAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_maxWalletAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "automatedMarketMakerPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dividendTokenBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dividendTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeFromFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeMultipleAccountsFromFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountDividendsInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountDividendsInfoAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimWait",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastProcessedIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfDividendTokenHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDividendsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradingIsEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExcludedFromFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processDividendTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellFeeIncreaseFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutomatedMarketMakerPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBUSDRewardsFeeBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBUSDRewardsFeesSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBurnFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDevFeeBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDevFeeSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketingFeeBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketingFeeSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setswapTokensAtAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradingEnabledTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Pair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Router",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateClaimWait",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDevWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDividendTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGasForProcessing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUniswapV2Router",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableDividendOf",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "DevWalletUpdated(address,address)": EventFragment;
    "ExcludeFromFees(address,bool)": EventFragment;
    "ExcludeMultipleAccountsFromFees(address[],bool)": EventFragment;
    "FixedSaleBuy(address,uint256,bool,uint256)": EventFragment;
    "GasForProcessingUpdated(uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProcessedDividendTracker(uint256,uint256,uint256,bool,uint256,address)": EventFragment;
    "SendDividends(uint256,uint256)": EventFragment;
    "SetAutomatedMarketMakerPair(address,bool)": EventFragment;
    "SwapAndLiquify(uint256,uint256,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "UpdateDividendTracker(address,address)": EventFragment;
    "UpdateUniswapV2Router(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DevWalletUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExcludeFromFees"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ExcludeMultipleAccountsFromFees"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FixedSaleBuy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GasForProcessingUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProcessedDividendTracker"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SendDividends"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SetAutomatedMarketMakerPair"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapAndLiquify"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateDividendTracker"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateUniswapV2Router"): EventFragment;
}

export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber] & {
    owner: string;
    spender: string;
    value: BigNumber;
  }
>;

export type DevWalletUpdatedEvent = TypedEvent<
  [string, string] & { newDevWallet: string; oldDevWallet: string }
>;

export type ExcludeFromFeesEvent = TypedEvent<
  [string, boolean] & { account: string; isExcluded: boolean }
>;

export type ExcludeMultipleAccountsFromFeesEvent = TypedEvent<
  [string[], boolean] & { accounts: string[]; isExcluded: boolean }
>;

export type FixedSaleBuyEvent = TypedEvent<
  [string, BigNumber, boolean, BigNumber] & {
    account: string;
    amount: BigNumber;
    earlyParticipant: boolean;
    numberOfBuyers: BigNumber;
  }
>;

export type GasForProcessingUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber] & { newValue: BigNumber; oldValue: BigNumber }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ProcessedDividendTrackerEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, boolean, BigNumber, string] & {
    iterations: BigNumber;
    claims: BigNumber;
    lastProcessedIndex: BigNumber;
    automatic: boolean;
    gas: BigNumber;
    processor: string;
  }
>;

export type SendDividendsEvent = TypedEvent<
  [BigNumber, BigNumber] & { tokensSwapped: BigNumber; amount: BigNumber }
>;

export type SetAutomatedMarketMakerPairEvent = TypedEvent<
  [string, boolean] & { pair: string; value: boolean }
>;

export type SwapAndLiquifyEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber] & {
    tokensSwapped: BigNumber;
    ethReceived: BigNumber;
    tokensIntoLiqudity: BigNumber;
  }
>;

export type TransferEvent = TypedEvent<
  [string, string, BigNumber] & { from: string; to: string; value: BigNumber }
>;

export type UpdateDividendTrackerEvent = TypedEvent<
  [string, string] & { newAddress: string; oldAddress: string }
>;

export type UpdateUniswapV2RouterEvent = TypedEvent<
  [string, string] & { newAddress: string; oldAddress: string }
>;

export class TestToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestTokenInterface;

  functions: {
    BUSD(overrides?: CallOverrides): Promise<[string]>;

    BUSDRewardsFeeBuy(overrides?: CallOverrides): Promise<[BigNumber]>;

    BUSDRewardsFeeSell(overrides?: CallOverrides): Promise<[BigNumber]>;

    BurnAddress(overrides?: CallOverrides): Promise<[string]>;

    BurnFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    DevFeeBuy(overrides?: CallOverrides): Promise<[BigNumber]>;

    DevFeeSell(overrides?: CallOverrides): Promise<[BigNumber]>;

    DevWallet(overrides?: CallOverrides): Promise<[string]>;

    MarketingFeeBuy(overrides?: CallOverrides): Promise<[BigNumber]>;

    MarketingFeeSell(overrides?: CallOverrides): Promise<[BigNumber]>;

    MarketingWallet(overrides?: CallOverrides): Promise<[string]>;

    SetmaxSellTransactionAmount(
      maxSellTransactionAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _maxTxAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    _maxWalletAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    automatedMarketMakerPairs(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    dividendTokenBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    dividendTracker(overrides?: CallOverrides): Promise<[string]>;

    excludeFromFees(
      account: string,
      excluded: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    excludeMultipleAccountsFromFees(
      accounts: string[],
      excluded: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAccountDividendsInfo(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;

    getAccountDividendsInfoAtIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;

    getClaimWait(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLastProcessedIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    getNumberOfDividendTokenHolders(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalDividendsDistributed(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTradingIsEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isExcludedFromFees(
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    processDividendTracker(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sellFeeIncreaseFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    setAutomatedMarketMakerPair(
      pair: string,
      value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBUSDRewardsFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBUSDRewardsFeesSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBurnFee(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDevFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDevFeeSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMarketingFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMarketingFeeSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setswapTokensAtAmount(
      swapTokensAtAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    tradingEnabledTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapV2Pair(overrides?: CallOverrides): Promise<[string]>;

    uniswapV2Router(overrides?: CallOverrides): Promise<[string]>;

    updateClaimWait(
      claimWait: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateDevWallet(
      newDevWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateDividendTracker(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateGasForProcessing(
      newValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateUniswapV2Router(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawableDividendOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  BUSD(overrides?: CallOverrides): Promise<string>;

  BUSDRewardsFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

  BUSDRewardsFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

  BurnAddress(overrides?: CallOverrides): Promise<string>;

  BurnFee(overrides?: CallOverrides): Promise<BigNumber>;

  DevFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

  DevFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

  DevWallet(overrides?: CallOverrides): Promise<string>;

  MarketingFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

  MarketingFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

  MarketingWallet(overrides?: CallOverrides): Promise<string>;

  SetmaxSellTransactionAmount(
    maxSellTransactionAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _maxTxAmount(overrides?: CallOverrides): Promise<BigNumber>;

  _maxWalletAmount(overrides?: CallOverrides): Promise<BigNumber>;

  allowance(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  automatedMarketMakerPairs(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  claim(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  dividendTokenBalanceOf(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  dividendTracker(overrides?: CallOverrides): Promise<string>;

  excludeFromFees(
    account: string,
    excluded: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  excludeMultipleAccountsFromFees(
    accounts: string[],
    excluded: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAccountDividendsInfo(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ]
  >;

  getAccountDividendsInfoAtIndex(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ]
  >;

  getClaimWait(overrides?: CallOverrides): Promise<BigNumber>;

  getLastProcessedIndex(overrides?: CallOverrides): Promise<BigNumber>;

  getNumberOfDividendTokenHolders(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalDividendsDistributed(overrides?: CallOverrides): Promise<BigNumber>;

  getTradingIsEnabled(overrides?: CallOverrides): Promise<boolean>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isExcludedFromFees(
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  processDividendTracker(
    gas: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sellFeeIncreaseFactor(overrides?: CallOverrides): Promise<BigNumber>;

  setAutomatedMarketMakerPair(
    pair: string,
    value: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBUSDRewardsFeeBuy(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBUSDRewardsFeesSell(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBurnFee(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDevFeeBuy(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDevFeeSell(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMarketingFeeBuy(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMarketingFeeSell(
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setswapTokensAtAmount(
    swapTokensAtAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalFees(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  tradingEnabledTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapV2Pair(overrides?: CallOverrides): Promise<string>;

  uniswapV2Router(overrides?: CallOverrides): Promise<string>;

  updateClaimWait(
    claimWait: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateDevWallet(
    newDevWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateDividendTracker(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateGasForProcessing(
    newValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateUniswapV2Router(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawableDividendOf(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    BUSD(overrides?: CallOverrides): Promise<string>;

    BUSDRewardsFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

    BUSDRewardsFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

    BurnAddress(overrides?: CallOverrides): Promise<string>;

    BurnFee(overrides?: CallOverrides): Promise<BigNumber>;

    DevFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

    DevFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

    DevWallet(overrides?: CallOverrides): Promise<string>;

    MarketingFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

    MarketingFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

    MarketingWallet(overrides?: CallOverrides): Promise<string>;

    SetmaxSellTransactionAmount(
      maxSellTransactionAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    _maxTxAmount(overrides?: CallOverrides): Promise<BigNumber>;

    _maxWalletAmount(overrides?: CallOverrides): Promise<BigNumber>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    automatedMarketMakerPairs(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    claim(overrides?: CallOverrides): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    dividendTokenBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dividendTracker(overrides?: CallOverrides): Promise<string>;

    excludeFromFees(
      account: string,
      excluded: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    excludeMultipleAccountsFromFees(
      accounts: string[],
      excluded: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    getAccountDividendsInfo(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;

    getAccountDividendsInfoAtIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;

    getClaimWait(overrides?: CallOverrides): Promise<BigNumber>;

    getLastProcessedIndex(overrides?: CallOverrides): Promise<BigNumber>;

    getNumberOfDividendTokenHolders(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDividendsDistributed(overrides?: CallOverrides): Promise<BigNumber>;

    getTradingIsEnabled(overrides?: CallOverrides): Promise<boolean>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isExcludedFromFees(
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    processDividendTracker(
      gas: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    sellFeeIncreaseFactor(overrides?: CallOverrides): Promise<BigNumber>;

    setAutomatedMarketMakerPair(
      pair: string,
      value: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setBUSDRewardsFeeBuy(
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setBUSDRewardsFeesSell(
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setBurnFee(val: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setDevFeeBuy(val: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setDevFeeSell(val: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setMarketingFeeBuy(
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMarketingFeeSell(
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setswapTokensAtAmount(
      swapTokensAtAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalFees(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    tradingEnabledTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapV2Pair(overrides?: CallOverrides): Promise<string>;

    uniswapV2Router(overrides?: CallOverrides): Promise<string>;

    updateClaimWait(
      claimWait: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDevWallet(
      newDevWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDividendTracker(
      newAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateGasForProcessing(
      newValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateUniswapV2Router(
      newAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawableDividendOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      spender?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    Approval(
      owner?: string | null,
      spender?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    "DevWalletUpdated(address,address)"(
      newDevWallet?: string | null,
      oldDevWallet?: string | null
    ): TypedEventFilter<
      [string, string],
      { newDevWallet: string; oldDevWallet: string }
    >;

    DevWalletUpdated(
      newDevWallet?: string | null,
      oldDevWallet?: string | null
    ): TypedEventFilter<
      [string, string],
      { newDevWallet: string; oldDevWallet: string }
    >;

    "ExcludeFromFees(address,bool)"(
      account?: string | null,
      isExcluded?: null
    ): TypedEventFilter<
      [string, boolean],
      { account: string; isExcluded: boolean }
    >;

    ExcludeFromFees(
      account?: string | null,
      isExcluded?: null
    ): TypedEventFilter<
      [string, boolean],
      { account: string; isExcluded: boolean }
    >;

    "ExcludeMultipleAccountsFromFees(address[],bool)"(
      accounts?: null,
      isExcluded?: null
    ): TypedEventFilter<
      [string[], boolean],
      { accounts: string[]; isExcluded: boolean }
    >;

    ExcludeMultipleAccountsFromFees(
      accounts?: null,
      isExcluded?: null
    ): TypedEventFilter<
      [string[], boolean],
      { accounts: string[]; isExcluded: boolean }
    >;

    "FixedSaleBuy(address,uint256,bool,uint256)"(
      account?: string | null,
      amount?: BigNumberish | null,
      earlyParticipant?: boolean | null,
      numberOfBuyers?: null
    ): TypedEventFilter<
      [string, BigNumber, boolean, BigNumber],
      {
        account: string;
        amount: BigNumber;
        earlyParticipant: boolean;
        numberOfBuyers: BigNumber;
      }
    >;

    FixedSaleBuy(
      account?: string | null,
      amount?: BigNumberish | null,
      earlyParticipant?: boolean | null,
      numberOfBuyers?: null
    ): TypedEventFilter<
      [string, BigNumber, boolean, BigNumber],
      {
        account: string;
        amount: BigNumber;
        earlyParticipant: boolean;
        numberOfBuyers: BigNumber;
      }
    >;

    "GasForProcessingUpdated(uint256,uint256)"(
      newValue?: BigNumberish | null,
      oldValue?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { newValue: BigNumber; oldValue: BigNumber }
    >;

    GasForProcessingUpdated(
      newValue?: BigNumberish | null,
      oldValue?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { newValue: BigNumber; oldValue: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ProcessedDividendTracker(uint256,uint256,uint256,bool,uint256,address)"(
      iterations?: null,
      claims?: null,
      lastProcessedIndex?: null,
      automatic?: boolean | null,
      gas?: null,
      processor?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, boolean, BigNumber, string],
      {
        iterations: BigNumber;
        claims: BigNumber;
        lastProcessedIndex: BigNumber;
        automatic: boolean;
        gas: BigNumber;
        processor: string;
      }
    >;

    ProcessedDividendTracker(
      iterations?: null,
      claims?: null,
      lastProcessedIndex?: null,
      automatic?: boolean | null,
      gas?: null,
      processor?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, boolean, BigNumber, string],
      {
        iterations: BigNumber;
        claims: BigNumber;
        lastProcessedIndex: BigNumber;
        automatic: boolean;
        gas: BigNumber;
        processor: string;
      }
    >;

    "SendDividends(uint256,uint256)"(
      tokensSwapped?: null,
      amount?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { tokensSwapped: BigNumber; amount: BigNumber }
    >;

    SendDividends(
      tokensSwapped?: null,
      amount?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { tokensSwapped: BigNumber; amount: BigNumber }
    >;

    "SetAutomatedMarketMakerPair(address,bool)"(
      pair?: string | null,
      value?: boolean | null
    ): TypedEventFilter<[string, boolean], { pair: string; value: boolean }>;

    SetAutomatedMarketMakerPair(
      pair?: string | null,
      value?: boolean | null
    ): TypedEventFilter<[string, boolean], { pair: string; value: boolean }>;

    "SwapAndLiquify(uint256,uint256,uint256)"(
      tokensSwapped?: null,
      ethReceived?: null,
      tokensIntoLiqudity?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      {
        tokensSwapped: BigNumber;
        ethReceived: BigNumber;
        tokensIntoLiqudity: BigNumber;
      }
    >;

    SwapAndLiquify(
      tokensSwapped?: null,
      ethReceived?: null,
      tokensIntoLiqudity?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      {
        tokensSwapped: BigNumber;
        ethReceived: BigNumber;
        tokensIntoLiqudity: BigNumber;
      }
    >;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; value: BigNumber }
    >;

    Transfer(
      from?: string | null,
      to?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; value: BigNumber }
    >;

    "UpdateDividendTracker(address,address)"(
      newAddress?: string | null,
      oldAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { newAddress: string; oldAddress: string }
    >;

    UpdateDividendTracker(
      newAddress?: string | null,
      oldAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { newAddress: string; oldAddress: string }
    >;

    "UpdateUniswapV2Router(address,address)"(
      newAddress?: string | null,
      oldAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { newAddress: string; oldAddress: string }
    >;

    UpdateUniswapV2Router(
      newAddress?: string | null,
      oldAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { newAddress: string; oldAddress: string }
    >;
  };

  estimateGas: {
    BUSD(overrides?: CallOverrides): Promise<BigNumber>;

    BUSDRewardsFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

    BUSDRewardsFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

    BurnAddress(overrides?: CallOverrides): Promise<BigNumber>;

    BurnFee(overrides?: CallOverrides): Promise<BigNumber>;

    DevFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

    DevFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

    DevWallet(overrides?: CallOverrides): Promise<BigNumber>;

    MarketingFeeBuy(overrides?: CallOverrides): Promise<BigNumber>;

    MarketingFeeSell(overrides?: CallOverrides): Promise<BigNumber>;

    MarketingWallet(overrides?: CallOverrides): Promise<BigNumber>;

    SetmaxSellTransactionAmount(
      maxSellTransactionAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _maxTxAmount(overrides?: CallOverrides): Promise<BigNumber>;

    _maxWalletAmount(overrides?: CallOverrides): Promise<BigNumber>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    automatedMarketMakerPairs(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    dividendTokenBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dividendTracker(overrides?: CallOverrides): Promise<BigNumber>;

    excludeFromFees(
      account: string,
      excluded: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    excludeMultipleAccountsFromFees(
      accounts: string[],
      excluded: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAccountDividendsInfo(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountDividendsInfoAtIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimWait(overrides?: CallOverrides): Promise<BigNumber>;

    getLastProcessedIndex(overrides?: CallOverrides): Promise<BigNumber>;

    getNumberOfDividendTokenHolders(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDividendsDistributed(overrides?: CallOverrides): Promise<BigNumber>;

    getTradingIsEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isExcludedFromFees(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    processDividendTracker(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sellFeeIncreaseFactor(overrides?: CallOverrides): Promise<BigNumber>;

    setAutomatedMarketMakerPair(
      pair: string,
      value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBUSDRewardsFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBUSDRewardsFeesSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBurnFee(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDevFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDevFeeSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMarketingFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMarketingFeeSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setswapTokensAtAmount(
      swapTokensAtAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalFees(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    tradingEnabledTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapV2Pair(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV2Router(overrides?: CallOverrides): Promise<BigNumber>;

    updateClaimWait(
      claimWait: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateDevWallet(
      newDevWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateDividendTracker(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateGasForProcessing(
      newValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateUniswapV2Router(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawableDividendOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BUSD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BUSDRewardsFeeBuy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BUSDRewardsFeeSell(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BurnAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BurnFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DevFeeBuy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DevFeeSell(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DevWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MarketingFeeBuy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MarketingFeeSell(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MarketingWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SetmaxSellTransactionAmount(
      maxSellTransactionAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _maxTxAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _maxWalletAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    automatedMarketMakerPairs(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    dividendTokenBalanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dividendTracker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeFromFees(
      account: string,
      excluded: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    excludeMultipleAccountsFromFees(
      accounts: string[],
      excluded: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAccountDividendsInfo(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountDividendsInfoAtIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaimWait(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastProcessedIndex(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumberOfDividendTokenHolders(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalDividendsDistributed(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradingIsEnabled(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isExcludedFromFees(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    processDividendTracker(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sellFeeIncreaseFactor(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAutomatedMarketMakerPair(
      pair: string,
      value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBUSDRewardsFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBUSDRewardsFeesSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBurnFee(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDevFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDevFeeSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMarketingFeeBuy(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMarketingFeeSell(
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setswapTokensAtAmount(
      swapTokensAtAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tradingEnabledTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapV2Pair(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapV2Router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateClaimWait(
      claimWait: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateDevWallet(
      newDevWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateDividendTracker(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateGasForProcessing(
      newValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateUniswapV2Router(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawableDividendOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
